import '../../models/country_codes_model.dart';

List<CountryCodesModel> countryCodeDatas = [
  CountryCodesModel(
    countryCode: "IN",
    name: "India",
    callingCode: "+91",
    flag: "flags/ind.png",
  ),
  CountryCodesModel(
    countryCode: "AF",
    name: "Afghanistan",
    callingCode: "+93",
    flag: "flags/afg.png",
  ),
  CountryCodesModel(
    countryCode: "AX",
    name: "Åland Islands",
    callingCode: "+358",
    flag: "flags/ala.png",
  ),
  CountryCodesModel(
    countryCode: "AL",
    name: "Albania",
    callingCode: "+355",
    flag: "flags/alb.png",
  ),
  CountryCodesModel(
    countryCode: "DZ",
    name: "Algeria",
    callingCode: "+213",
    flag: "flags/dza.png",
  ),
  CountryCodesModel(
    countryCode: "AS",
    name: "American Samoa",
    callingCode: "+1684",
    flag: "flags/asm.png",
  ),
  CountryCodesModel(
    countryCode: "AD",
    name: "Andorra",
    callingCode: "+376",
    flag: "flags/and.png",
  ),
  CountryCodesModel(
    countryCode: "AO",
    name: "Angola",
    callingCode: "+244",
    flag: "flags/ago.png",
  ),
  CountryCodesModel(
    countryCode: "AI",
    name: "Anguilla",
    callingCode: "+1264",
    flag: "flags/aia.png",
  ),
  CountryCodesModel(
    countryCode: "AQ",
    name: "Antarctica",
    callingCode: "+672",
    flag: "flags/ata.png",
  ),
  CountryCodesModel(
    countryCode: "AG",
    name: "Antigua and Barbuda",
    callingCode: "+1268",
    flag: "flags/atg.png",
  ),
  CountryCodesModel(
    countryCode: "AR",
    name: "Argentina",
    callingCode: "+54",
    flag: "flags/arg.png",
  ),
  CountryCodesModel(
    countryCode: "AM",
    name: "Armenia",
    callingCode: "+374",
    flag: "flags/arm.png",
  ),
  CountryCodesModel(
    countryCode: "AW",
    name: "Aruba",
    callingCode: "+297",
    flag: "flags/abw.png",
  ),
  CountryCodesModel(
    countryCode: "AU",
    name: "Australia",
    callingCode: "+61",
    flag: "flags/aus.png",
  ),
  CountryCodesModel(
    countryCode: "AT",
    name: "Austria",
    callingCode: "+43",
    flag: "flags/aut.png",
  ),
  CountryCodesModel(
    countryCode: "AZ",
    name: "Azerbaijan",
    callingCode: "+994",
    flag: "flags/aze.png",
  ),
  CountryCodesModel(
    countryCode: "BS",
    name: "Bahamas",
    callingCode: "+1242",
    flag: "flags/bhs.png",
  ),
  CountryCodesModel(
    countryCode: "BH",
    name: "Bahrain",
    callingCode: "+973",
    flag: "flags/bhr.png",
  ),
  CountryCodesModel(
    countryCode: "BD",
    name: "Bangladesh",
    callingCode: "+880",
    flag: "flags/bgd.png",
  ),
  CountryCodesModel(
    countryCode: "BB",
    name: "Barbados",
    callingCode: "+1246",
    flag: "flags/brb.png",
  ),
  CountryCodesModel(
    countryCode: "BY",
    name: "Belarus",
    callingCode: "+375",
    flag: "flags/blr.png",
  ),
  CountryCodesModel(
    countryCode: "BE",
    name: "Belgium",
    callingCode: "+32",
    flag: "flags/bel.png",
  ),
  CountryCodesModel(
    countryCode: "BZ",
    name: "Belize",
    callingCode: "+501",
    flag: "flags/blz.png",
  ),
  CountryCodesModel(
    countryCode: "BJ",
    name: "Benin",
    callingCode: "+229",
    flag: "flags/ben.png",
  ),
  CountryCodesModel(
    countryCode: "BM",
    name: "Bermuda",
    callingCode: "+1441",
    flag: "flags/bmu.png",
  ),
  CountryCodesModel(
    countryCode: "BT",
    name: "Bhutan",
    callingCode: "+975",
    flag: "flags/btn.png",
  ),
  CountryCodesModel(
    countryCode: "BO",
    name: "Bolivia (Plurinational State of,)",
    callingCode: "+591",
    flag: "flags/bol.png",
  ),
  CountryCodesModel(
    countryCode: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    callingCode: "+5997",
    flag: "flags/bes.png",
  ),
  CountryCodesModel(
    countryCode: "BA",
    name: "Bosnia and Herzegovina",
    callingCode: "+387",
    flag: "flags/bih.png",
  ),
  CountryCodesModel(
    countryCode: "BW",
    name: "Botswana",
    callingCode: "+267",
    flag: "flags/bwa.png",
  ),
  CountryCodesModel(
    countryCode: "BV",
    name: "Bouvet Island",
    callingCode: "+55",
    flag: "flags/bvt.png",
  ),
  CountryCodesModel(
    countryCode: "BR",
    name: "Brazil",
    callingCode: "+55",
    flag: "flags/bra.png",
  ),
  CountryCodesModel(
    countryCode: "IO",
    name: "British Indian Ocean Territory",
    callingCode: "+246",
    flag: "flags/iot.png",
  ),
  CountryCodesModel(
    countryCode: "UM",
    name: "United States Minor Outlying Islands",
    callingCode: "+246",
    flag: "flags/umi.png",
  ),
  CountryCodesModel(
    countryCode: "VG",
    name: "Virgin Islands (British,)",
    callingCode: "+1284",
    flag: "flags/vgb.png",
  ),
  CountryCodesModel(
    countryCode: "VI",
    name: "Virgin Islands (U.S.,)",
    callingCode: "+1 340",
    flag: "flags/vir.png",
  ),
  CountryCodesModel(
    countryCode: "BN",
    name: "Brunei Darussalam",
    callingCode: "+673",
    flag: "flags/brn.png",
  ),
  CountryCodesModel(
    countryCode: "BG",
    name: "Bulgaria",
    callingCode: "+359",
    flag: "flags/bgr.png",
  ),
  CountryCodesModel(
    countryCode: "BF",
    name: "Burkina Faso",
    callingCode: "+226",
    flag: "flags/bfa.png",
  ),
  CountryCodesModel(
    countryCode: "BI",
    name: "Burundi",
    callingCode: "+257",
    flag: "flags/bdi.png",
  ),
  CountryCodesModel(
    countryCode: "KH",
    name: "Cambodia",
    callingCode: "+855",
    flag: "flags/khm.png",
  ),
  CountryCodesModel(
    countryCode: "CM",
    name: "Cameroon",
    callingCode: "+237",
    flag: "flags/cmr.png",
  ),
  CountryCodesModel(
    countryCode: "CA",
    name: "Canada",
    callingCode: "+1",
    flag: "flags/can.png",
  ),
  CountryCodesModel(
    countryCode: "CV",
    name: "Cabo Verde",
    callingCode: "+238",
    flag: "flags/cpv.png",
  ),
  CountryCodesModel(
    countryCode: "KY",
    name: "Cayman Islands",
    callingCode: "+1345",
    flag: "flags/cym.png",
  ),
  CountryCodesModel(
    countryCode: "CF",
    name: "Central African Republic",
    callingCode: "+236",
    flag: "flags/caf.png",
  ),
  CountryCodesModel(
    countryCode: "TD",
    name: "Chad",
    callingCode: "+235",
    flag: "flags/tcd.png",
  ),
  CountryCodesModel(
    countryCode: "CL",
    name: "Chile",
    callingCode: "+56",
    flag: "flags/chl.png",
  ),
  CountryCodesModel(
    countryCode: "CN",
    name: "China",
    callingCode: "+86",
    flag: "flags/chn.png",
  ),
  CountryCodesModel(
    countryCode: "CX",
    name: "Christmas Island",
    callingCode: "+61",
    flag: "flags/cxr.png",
  ),
  CountryCodesModel(
    countryCode: "CC",
    name: "Cocos (Keeling,) Islands",
    callingCode: "+61",
    flag: "flags/cck.png",
  ),
  CountryCodesModel(
    countryCode: "CO",
    name: "Colombia",
    callingCode: "+57",
    flag: "flags/col.png",
  ),
  CountryCodesModel(
    countryCode: "KM",
    name: "Comoros",
    callingCode: "+269",
    flag: "flags/com.png",
  ),
  CountryCodesModel(
    countryCode: "CG",
    name: "Congo",
    callingCode: "+242",
    flag: "flags/cog.png",
  ),
  CountryCodesModel(
    countryCode: "CD",
    name: "Congo (Democratic Republic of the,)",
    callingCode: "+243",
    flag: "flags/cod.png",
  ),
  CountryCodesModel(
    countryCode: "CK",
    name: "Cook Islands",
    callingCode: "+682",
    flag: "flags/cok.png",
  ),
  CountryCodesModel(
    countryCode: "CR",
    name: "Costa Rica",
    callingCode: "+506",
    flag: "flags/cri.png",
  ),
  CountryCodesModel(
    countryCode: "HR",
    name: "Croatia",
    callingCode: "+385",
    flag: "flags/hrv.png",
  ),
  CountryCodesModel(
    countryCode: "CU",
    name: "Cuba",
    callingCode: "+53",
    flag: "flags/cub.png",
  ),
  CountryCodesModel(
    countryCode: "CW",
    name: "Curaçao",
    callingCode: "+599",
    flag: "flags/cuw.png",
  ),
  CountryCodesModel(
    countryCode: "CY",
    name: "Cyprus",
    callingCode: "+357",
    flag: "flags/cyp.png",
  ),
  CountryCodesModel(
    countryCode: "CZ",
    name: "Czech Republic",
    callingCode: "+420",
    flag: "flags/cze.png",
  ),
  CountryCodesModel(
    countryCode: "DK",
    name: "Denmark",
    callingCode: "+45",
    flag: "flags/dnk.png",
  ),
  CountryCodesModel(
    countryCode: "DJ",
    name: "Djibouti",
    callingCode: "+253",
    flag: "flags/dji.png",
  ),
  CountryCodesModel(
    countryCode: "DM",
    name: "Dominica",
    callingCode: "+1767",
    flag: "flags/dma.png",
  ),
  CountryCodesModel(
    countryCode: "DO",
    name: "Dominican Republic",
    callingCode: "+1809",
    flag: "flags/dom.png",
  ),
  CountryCodesModel(
    countryCode: "EC",
    name: "Ecuador",
    callingCode: "+593",
    flag: "flags/ecu.png",
  ),
  CountryCodesModel(
    countryCode: "EG",
    name: "Egypt",
    callingCode: "+20",
    flag: "flags/egy.png",
  ),
  CountryCodesModel(
    countryCode: "SV",
    name: "El Salvador",
    callingCode: "+503",
    flag: "flags/slv.png",
  ),
  CountryCodesModel(
    countryCode: "GQ",
    name: "Equatorial Guinea",
    callingCode: "+240",
    flag: "flags/gnq.png",
  ),
  CountryCodesModel(
    countryCode: "ER",
    name: "Eritrea",
    callingCode: "+291",
    flag: "flags/eri.png",
  ),
  CountryCodesModel(
    countryCode: "EE",
    name: "Estonia",
    callingCode: "+372",
    flag: "flags/est.png",
  ),
  CountryCodesModel(
    countryCode: "ET",
    name: "Ethiopia",
    callingCode: "+251",
    flag: "flags/eth.png",
  ),
  CountryCodesModel(
    countryCode: "FK",
    name: "Falkland Islands (Malvinas,)",
    callingCode: "+500",
    flag: "flags/flk.png",
  ),
  CountryCodesModel(
    countryCode: "FO",
    name: "Faroe Islands",
    callingCode: "+298",
    flag: "flags/fro.png",
  ),
  CountryCodesModel(
    countryCode: "FJ",
    name: "Fiji",
    callingCode: "+679",
    flag: "flags/fji.png",
  ),
  CountryCodesModel(
    countryCode: "FI",
    name: "Finland",
    callingCode: "+358",
    flag: "flags/fin.png",
  ),
  CountryCodesModel(
    countryCode: "FR",
    name: "France",
    callingCode: "+33",
    flag: "flags/fra.png",
  ),
  CountryCodesModel(
    countryCode: "GF",
    name: "French Guiana",
    callingCode: "+594",
    flag: "flags/guf.png",
  ),
  CountryCodesModel(
    countryCode: "PF",
    name: "French Polynesia",
    callingCode: "+689",
    flag: "flags/pyf.png",
  ),
  CountryCodesModel(
    countryCode: "TF",
    name: "French Southern Territories",
    callingCode: "+262",
    flag: "flags/atf.png",
  ),
  CountryCodesModel(
    countryCode: "GA",
    name: "Gabon",
    callingCode: "+241",
    flag: "flags/gab.png",
  ),
  CountryCodesModel(
    countryCode: "GM",
    name: "Gambia",
    callingCode: "+220",
    flag: "flags/gmb.png",
  ),
  CountryCodesModel(
    countryCode: "GE",
    name: "Georgia",
    callingCode: "+995",
    flag: "flags/geo.png",
  ),
  CountryCodesModel(
    countryCode: "DE",
    name: "Germany",
    callingCode: "+49",
    flag: "flags/deu.png",
  ),
  CountryCodesModel(
    countryCode: "GH",
    name: "Ghana",
    callingCode: "+233",
    flag: "flags/gha.png",
  ),
  CountryCodesModel(
    countryCode: "GI",
    name: "Gibraltar",
    callingCode: "+350",
    flag: "flags/gib.png",
  ),
  CountryCodesModel(
    countryCode: "GR",
    name: "Greece",
    callingCode: "+30",
    flag: "flags/grc.png",
  ),
  CountryCodesModel(
    countryCode: "GL",
    name: "Greenland",
    callingCode: "+299",
    flag: "flags/grl.png",
  ),
  CountryCodesModel(
    countryCode: "GD",
    name: "Grenada",
    callingCode: "+1473",
    flag: "flags/grd.png",
  ),
  CountryCodesModel(
    countryCode: "GP",
    name: "Guadeloupe",
    callingCode: "+590",
    flag: "flags/glp.png",
  ),
  CountryCodesModel(
    countryCode: "GU",
    name: "Guam",
    callingCode: "+1671",
    flag: "flags/gum.png",
  ),
  CountryCodesModel(
    countryCode: "GT",
    name: "Guatemala",
    callingCode: "+502",
    flag: "flags/gtm.png",
  ),
  CountryCodesModel(
    countryCode: "GG",
    name: "Guernsey",
    callingCode: "+44",
    flag: "flags/ggy.png",
  ),
  CountryCodesModel(
    countryCode: "GN",
    name: "Guinea",
    callingCode: "+224",
    flag: "flags/gin.png",
  ),
  CountryCodesModel(
    countryCode: "GW",
    name: "Guinea-Bissau",
    callingCode: "+245",
    flag: "flags/gnb.png",
  ),
  CountryCodesModel(
    countryCode: "GY",
    name: "Guyana",
    callingCode: "+592",
    flag: "flags/guy.png",
  ),
  CountryCodesModel(
    countryCode: "HT",
    name: "Haiti",
    callingCode: "+509",
    flag: "flags/hti.png",
  ),
  CountryCodesModel(
    countryCode: "HM",
    name: "Heard Island and McDonald Islands",
    callingCode: "+672",
    flag: "flags/hmd.png",
  ),
  CountryCodesModel(
    countryCode: "VA",
    name: "Holy See",
    callingCode: "+379",
    flag: "flags/vat.png",
  ),
  CountryCodesModel(
    countryCode: "HN",
    name: "Honduras",
    callingCode: "+504",
    flag: "flags/hnd.png",
  ),
  CountryCodesModel(
    countryCode: "HK",
    name: "Hong Kong",
    callingCode: "+852",
    flag: "flags/hkg.png",
  ),
  CountryCodesModel(
    countryCode: "HU",
    name: "Hungary",
    callingCode: "+36",
    flag: "flags/hun.png",
  ),
  CountryCodesModel(
    countryCode: "IS",
    name: "Iceland",
    callingCode: "+354",
    flag: "flags/isl.png",
  ),
  CountryCodesModel(
    countryCode: "ID",
    name: "Indonesia",
    callingCode: "+62",
    flag: "flags/idn.png",
  ),
  CountryCodesModel(
    countryCode: "CI",
    name: "Côte d'Ivoire",
    callingCode: "+225",
    flag: "flags/civ.png",
  ),
  CountryCodesModel(
    countryCode: "IR",
    name: "Iran (Islamic Republic of,)",
    callingCode: "+98",
    flag: "flags/irn.png",
  ),
  CountryCodesModel(
    countryCode: "IQ",
    name: "Iraq",
    callingCode: "+964",
    flag: "flags/irq.png",
  ),
  CountryCodesModel(
    countryCode: "IE",
    name: "Ireland",
    callingCode: "+353",
    flag: "flags/irl.png",
  ),
  CountryCodesModel(
    countryCode: "IM",
    name: "Isle of Man",
    callingCode: "+44",
    flag: "flags/imn.png",
  ),
  CountryCodesModel(
    countryCode: "IL",
    name: "Israel",
    callingCode: "+972",
    flag: "flags/isr.png",
  ),
  CountryCodesModel(
    countryCode: "IT",
    name: "Italy",
    callingCode: "+39",
    flag: "flags/ita.png",
  ),
  CountryCodesModel(
    countryCode: "JM",
    name: "Jamaica",
    callingCode: "+1876",
    flag: "flags/jam.png",
  ),
  CountryCodesModel(
    countryCode: "JP",
    name: "Japan",
    callingCode: "+81",
    flag: "flags/jpn.png",
  ),
  CountryCodesModel(
    countryCode: "JE",
    name: "Jersey",
    callingCode: "+44",
    flag: "flags/jey.png",
  ),
  CountryCodesModel(
    countryCode: "JO",
    name: "Jordan",
    callingCode: "+962",
    flag: "flags/jor.png",
  ),
  CountryCodesModel(
    countryCode: "KZ",
    name: "Kazakhstan",
    callingCode: "+76",
    flag: "flags/kaz.png",
  ),
  CountryCodesModel(
    countryCode: "KE",
    name: "Kenya",
    callingCode: "+254",
    flag: "flags/ken.png",
  ),
  CountryCodesModel(
    countryCode: "KI",
    name: "Kiribati",
    callingCode: "+686",
    flag: "flags/kir.png",
  ),
  CountryCodesModel(
    countryCode: "KW",
    name: "Kuwait",
    callingCode: "+965",
    flag: "flags/kwt.png",
  ),
  CountryCodesModel(
    countryCode: "KG",
    name: "Kyrgyzstan",
    callingCode: "+996",
    flag: "flags/kgz.png",
  ),
  CountryCodesModel(
    countryCode: "LA",
    name: "Lao People's Democratic Republic",
    callingCode: "+856",
    flag: "flags/lao.png",
  ),
  CountryCodesModel(
    countryCode: "LV",
    name: "Latvia",
    callingCode: "+371",
    flag: "flags/lva.png",
  ),
  CountryCodesModel(
    countryCode: "LB",
    name: "Lebanon",
    callingCode: "+961",
    flag: "flags/lbn.png",
  ),
  CountryCodesModel(
    countryCode: "LS",
    name: "Lesotho",
    callingCode: "+266",
    flag: "flags/lso.png",
  ),
  CountryCodesModel(
    countryCode: "LR",
    name: "Liberia",
    callingCode: "+231",
    flag: "flags/lbr.png",
  ),
  CountryCodesModel(
    countryCode: "LY",
    name: "Libya",
    callingCode: "+218",
    flag: "flags/lby.png",
  ),
  CountryCodesModel(
    countryCode: "LI",
    name: "Liechtenstein",
    callingCode: "+423",
    flag: "flags/lie.png",
  ),
  CountryCodesModel(
    countryCode: "LT",
    name: "Lithuania",
    callingCode: "+370",
    flag: "flags/ltu.png",
  ),
  CountryCodesModel(
    countryCode: "LU",
    name: "Luxembourg",
    callingCode: "+352",
    flag: "flags/lux.png",
  ),
  CountryCodesModel(
    countryCode: "MO",
    name: "Macao",
    callingCode: "+853",
    flag: "flags/mac.png",
  ),
  CountryCodesModel(
    countryCode: "MK",
    name: "Macedonia (the former Yugoslav Republic of,)",
    callingCode: "+389",
    flag: "flags/mkd.png",
  ),
  CountryCodesModel(
    countryCode: "MG",
    name: "Madagascar",
    callingCode: "+261",
    flag: "flags/mdg.png",
  ),
  CountryCodesModel(
    countryCode: "MW",
    name: "Malawi",
    callingCode: "+265",
    flag: "flags/mwi.png",
  ),
  CountryCodesModel(
    countryCode: "MY",
    name: "Malaysia",
    callingCode: "+60",
    flag: "flags/mys.png",
  ),
  CountryCodesModel(
    countryCode: "MV",
    name: "Maldives",
    callingCode: "+960",
    flag: "flags/mdv.png",
  ),
  CountryCodesModel(
    countryCode: "ML",
    name: "Mali",
    callingCode: "+223",
    flag: "flags/mli.png",
  ),
  CountryCodesModel(
    countryCode: "MT",
    name: "Malta",
    callingCode: "+356",
    flag: "flags/mlt.png",
  ),
  CountryCodesModel(
    countryCode: "MH",
    name: "Marshall Islands",
    callingCode: "+692",
    flag: "flags/mhl.png",
  ),
  CountryCodesModel(
    countryCode: "MQ",
    name: "Martinique",
    callingCode: "+596",
    flag: "flags/mtq.png",
  ),
  CountryCodesModel(
    countryCode: "MR",
    name: "Mauritania",
    callingCode: "+222",
    flag: "flags/mrt.png",
  ),
  CountryCodesModel(
    countryCode: "MU",
    name: "Mauritius",
    callingCode: "+230",
    flag: "flags/mus.png",
  ),
  CountryCodesModel(
    countryCode: "YT",
    name: "Mayotte",
    callingCode: "+262",
    flag: "flags/myt.png",
  ),
  CountryCodesModel(
    countryCode: "MX",
    name: "Mexico",
    callingCode: "+52",
    flag: "flags/mex.png",
  ),
  CountryCodesModel(
    countryCode: "FM",
    name: "Micronesia (Federated States of,)",
    callingCode: "+691",
    flag: "flags/fsm.png",
  ),
  CountryCodesModel(
    countryCode: "MD",
    name: "Moldova (Republic of,)",
    callingCode: "+373",
    flag: "flags/mda.png",
  ),
  CountryCodesModel(
    countryCode: "MC",
    name: "Monaco",
    callingCode: "+377",
    flag: "flags/mco.png",
  ),
  CountryCodesModel(
    countryCode: "MN",
    name: "Mongolia",
    callingCode: "+976",
    flag: "flags/mng.png",
  ),
  CountryCodesModel(
    countryCode: "ME",
    name: "Montenegro",
    callingCode: "+382",
    flag: "flags/mne.png",
  ),
  CountryCodesModel(
    countryCode: "MS",
    name: "Montserrat",
    callingCode: "+1664",
    flag: "flags/msr.png",
  ),
  CountryCodesModel(
    countryCode: "MA",
    name: "Morocco",
    callingCode: "+212",
    flag: "flags/mar.png",
  ),
  CountryCodesModel(
    countryCode: "MZ",
    name: "Mozambique",
    callingCode: "+258",
    flag: "flags/moz.png",
  ),
  CountryCodesModel(
    countryCode: "MM",
    name: "Myanmar",
    callingCode: "+95",
    flag: "flags/mmr.png",
  ),
  CountryCodesModel(
    countryCode: "NA",
    name: "Namibia",
    callingCode: "+264",
    flag: "flags/nam.png",
  ),
  CountryCodesModel(
    countryCode: "NR",
    name: "Nauru",
    callingCode: "+674",
    flag: "flags/nru.png",
  ),
  CountryCodesModel(
    countryCode: "NP",
    name: "Nepal",
    callingCode: "+977",
    flag: "flags/npl.png",
  ),
  CountryCodesModel(
    countryCode: "NL",
    name: "Netherlands",
    callingCode: "+31",
    flag: "flags/nld.png",
  ),
  CountryCodesModel(
    countryCode: "NC",
    name: "New Caledonia",
    callingCode: "+687",
    flag: "flags/ncl.png",
  ),
  CountryCodesModel(
    countryCode: "NZ",
    name: "New Zealand",
    callingCode: "+64",
    flag: "flags/nzl.png",
  ),
  CountryCodesModel(
    countryCode: "NI",
    name: "Nicaragua",
    callingCode: "+505",
    flag: "flags/nic.png",
  ),
  CountryCodesModel(
    countryCode: "NE",
    name: "Niger",
    callingCode: "+227",
    flag: "flags/ner.png",
  ),
  CountryCodesModel(
    countryCode: "NG",
    name: "Nigeria",
    callingCode: "+234",
    flag: "flags/nga.png",
  ),
  CountryCodesModel(
    countryCode: "NU",
    name: "Niue",
    callingCode: "+683",
    flag: "flags/niu.png",
  ),
  CountryCodesModel(
    countryCode: "NF",
    name: "Norfolk Island",
    callingCode: "+672",
    flag: "flags/nfk.png",
  ),
  CountryCodesModel(
    countryCode: "KP",
    name: "Korea (Democratic People's Republic of,)",
    callingCode: "+850",
    flag: "flags/prk.png",
  ),
  CountryCodesModel(
    countryCode: "MP",
    name: "Northern Mariana Islands",
    callingCode: "+1670",
    flag: "flags/mnp.png",
  ),
  CountryCodesModel(
    countryCode: "NO",
    name: "Norway",
    callingCode: "+47",
    flag: "flags/nor.png",
  ),
  CountryCodesModel(
    countryCode: "OM",
    name: "Oman",
    callingCode: "+968",
    flag: "flags/omn.png",
  ),
  CountryCodesModel(
    countryCode: "PK",
    name: "Pakistan",
    callingCode: "+92",
    flag: "flags/pak.png",
  ),
  CountryCodesModel(
    countryCode: "PW",
    name: "Palau",
    callingCode: "+680",
    flag: "flags/plw.png",
  ),
  CountryCodesModel(
    countryCode: "PS",
    name: "Palestine, State of",
    callingCode: "+970",
    flag: "flags/pse.png",
  ),
  CountryCodesModel(
    countryCode: "PA",
    name: "Panama",
    callingCode: "+507",
    flag: "flags/pan.png",
  ),
  CountryCodesModel(
    countryCode: "PG",
    name: "Papua New Guinea",
    callingCode: "+675",
    flag: "flags/png.png",
  ),
  CountryCodesModel(
    countryCode: "PY",
    name: "Paraguay",
    callingCode: "+595",
    flag: "flags/pry.png",
  ),
  CountryCodesModel(
    countryCode: "PE",
    name: "Peru",
    callingCode: "+51",
    flag: "flags/per.png",
  ),
  CountryCodesModel(
    countryCode: "PH",
    name: "Philippines",
    callingCode: "+63",
    flag: "flags/phl.png",
  ),
  CountryCodesModel(
    countryCode: "PN",
    name: "Pitcairn",
    callingCode: "+64",
    flag: "flags/pcn.png",
  ),
  CountryCodesModel(
    countryCode: "PL",
    name: "Poland",
    callingCode: "+48",
    flag: "flags/pol.png",
  ),
  CountryCodesModel(
    countryCode: "PT",
    name: "Portugal",
    callingCode: "+351",
    flag: "flags/prt.png",
  ),
  CountryCodesModel(
    countryCode: "PR",
    name: "Puerto Rico",
    callingCode: "+1787",
    flag: "flags/pri.png",
  ),
  CountryCodesModel(
    countryCode: "QA",
    name: "Qatar",
    callingCode: "+974",
    flag: "flags/qat.png",
  ),
  CountryCodesModel(
    countryCode: "XK",
    name: "Republic of Kosovo",
    callingCode: "+383",
    flag: "flags/kos.png",
  ),
  CountryCodesModel(
    countryCode: "RE",
    name: "Réunion",
    callingCode: "+262",
    flag: "flags/reu.png",
  ),
  CountryCodesModel(
    countryCode: "RO",
    name: "Romania",
    callingCode: "+40",
    flag: "flags/rou.png",
  ),
  CountryCodesModel(
    countryCode: "RU",
    name: "Russian Federation",
    callingCode: "+7",
    flag: "flags/rus.png",
  ),
  CountryCodesModel(
    countryCode: "RW",
    name: "Rwanda",
    callingCode: "+250",
    flag: "flags/rwa.png",
  ),
  CountryCodesModel(
    countryCode: "BL",
    name: "Saint Barthélemy",
    callingCode: "+590",
    flag: "flags/blm.png",
  ),
  CountryCodesModel(
    countryCode: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    callingCode: "+290",
    flag: "flags/shn.png",
  ),
  CountryCodesModel(
    countryCode: "KN",
    name: "Saint Kitts and Nevis",
    callingCode: "+1869",
    flag: "flags/kna.png",
  ),
  CountryCodesModel(
    countryCode: "LC",
    name: "Saint Lucia",
    callingCode: "+1758",
    flag: "flags/lca.png",
  ),
  CountryCodesModel(
    countryCode: "MF",
    name: "Saint Martin (French part,)",
    callingCode: "+590",
    flag: "flags/maf.png",
  ),
  CountryCodesModel(
    countryCode: "PM",
    name: "Saint Pierre and Miquelon",
    callingCode: "+508",
    flag: "flags/spm.png",
  ),
  CountryCodesModel(
    countryCode: "VC",
    name: "Saint Vincent and the Grenadines",
    callingCode: "+1784",
    flag: "flags/vct.png",
  ),
  CountryCodesModel(
    countryCode: "WS",
    name: "Samoa",
    callingCode: "+685",
    flag: "flags/wsm.png",
  ),
  CountryCodesModel(
    countryCode: "SM",
    name: "San Marino",
    callingCode: "+378",
    flag: "flags/smr.png",
  ),
  CountryCodesModel(
    countryCode: "ST",
    name: "Sao Tome and Principe",
    callingCode: "+239",
    flag: "flags/stp.png",
  ),
  CountryCodesModel(
    countryCode: "SA",
    name: "Saudi Arabia",
    callingCode: "+966",
    flag: "flags/sau.png",
  ),
  CountryCodesModel(
    countryCode: "SN",
    name: "Senegal",
    callingCode: "+221",
    flag: "flags/sen.png",
  ),
  CountryCodesModel(
    countryCode: "RS",
    name: "Serbia",
    callingCode: "+381",
    flag: "flags/srb.png",
  ),
  CountryCodesModel(
    countryCode: "SC",
    name: "Seychelles",
    callingCode: "+248",
    flag: "flags/syc.png",
  ),
  CountryCodesModel(
    countryCode: "SL",
    name: "Sierra Leone",
    callingCode: "+232",
    flag: "flags/sle.png",
  ),
  CountryCodesModel(
    countryCode: "SG",
    name: "Singapore",
    callingCode: "+65",
    flag: "flags/sgp.png",
  ),
  CountryCodesModel(
    countryCode: "SX",
    name: "Sint Maarten (Dutch part,)",
    callingCode: "+1721",
    flag: "flags/sxm.png",
  ),
  CountryCodesModel(
    countryCode: "SK",
    name: "Slovakia",
    callingCode: "+421",
    flag: "flags/svk.png",
  ),
  CountryCodesModel(
    countryCode: "SI",
    name: "Slovenia",
    callingCode: "+386",
    flag: "flags/svn.png",
  ),
  CountryCodesModel(
    countryCode: "SB",
    name: "Solomon Islands",
    callingCode: "+677",
    flag: "flags/slb.png",
  ),
  CountryCodesModel(
    countryCode: "SO",
    name: "Somalia",
    callingCode: "+252",
    flag: "flags/som.png",
  ),
  CountryCodesModel(
    countryCode: "ZA",
    name: "South Africa",
    callingCode: "+27",
    flag: "flags/zaf.png",
  ),
  CountryCodesModel(
    countryCode: "GS",
    name: "South Georgia and the South Sandwich Islands",
    callingCode: "+500",
    flag: "flags/sgs.png",
  ),
  CountryCodesModel(
    countryCode: "KR",
    name: "Korea (Republic of,)",
    callingCode: "+82",
    flag: "flags/kor.png",
  ),
  CountryCodesModel(
    countryCode: "SS",
    name: "South Sudan",
    callingCode: "+211",
    flag: "flags/ssd.png",
  ),
  CountryCodesModel(
    countryCode: "ES",
    name: "Spain",
    callingCode: "+34",
    flag: "flags/esp.png",
  ),
  CountryCodesModel(
    countryCode: "LK",
    name: "Sri Lanka",
    callingCode: "+94",
    flag: "flags/lka.png",
  ),
  CountryCodesModel(
    countryCode: "SD",
    name: "Sudan",
    callingCode: "+249",
    flag: "flags/sdn.png",
  ),
  CountryCodesModel(
    countryCode: "SR",
    name: "Suriname",
    callingCode: "+597",
    flag: "flags/sur.png",
  ),
  CountryCodesModel(
    countryCode: "SJ",
    name: "Svalbard and Jan Mayen",
    callingCode: "+4779",
    flag: "flags/sjm.png",
  ),
  CountryCodesModel(
    countryCode: "SZ",
    name: "Swaziland",
    callingCode: "+268",
    flag: "flags/swz.png",
  ),
  CountryCodesModel(
    countryCode: "SE",
    name: "Sweden",
    callingCode: "+46",
    flag: "flags/swe.png",
  ),
  CountryCodesModel(
    countryCode: "CH",
    name: "Switzerland",
    callingCode: "+41",
    flag: "flags/che.png",
  ),
  CountryCodesModel(
    countryCode: "SY",
    name: "Syrian Arab Republic",
    callingCode: "+963",
    flag: "flags/syr.png",
  ),
  CountryCodesModel(
    countryCode: "TW",
    name: "Taiwan",
    callingCode: "+886",
    flag: "flags/twn.png",
  ),
  CountryCodesModel(
    countryCode: "TJ",
    name: "Tajikistan",
    callingCode: "+992",
    flag: "flags/tjk.png",
  ),
  CountryCodesModel(
    countryCode: "TZ",
    name: "Tanzania, United Republic of",
    callingCode: "+255",
    flag: "flags/tza.png",
  ),
  CountryCodesModel(
    countryCode: "TH",
    name: "Thailand",
    callingCode: "+66",
    flag: "flags/tha.png",
  ),
  CountryCodesModel(
    countryCode: "TL",
    name: "Timor-Leste",
    callingCode: "+670",
    flag: "flags/tls.png",
  ),
  CountryCodesModel(
    countryCode: "TG",
    name: "Togo",
    callingCode: "+228",
    flag: "flags/tgo.png",
  ),
  CountryCodesModel(
    countryCode: "TK",
    name: "Tokelau",
    callingCode: "+690",
    flag: "flags/tkl.png",
  ),
  CountryCodesModel(
    countryCode: "TO",
    name: "Tonga",
    callingCode: "+676",
    flag: "flags/ton.png",
  ),
  CountryCodesModel(
    countryCode: "TT",
    name: "Trinidad and Tobago",
    callingCode: "+1868",
    flag: "flags/tto.png",
  ),
  CountryCodesModel(
    countryCode: "TN",
    name: "Tunisia",
    callingCode: "+216",
    flag: "flags/tun.png",
  ),
  CountryCodesModel(
    countryCode: "TR",
    name: "Turkey",
    callingCode: "+90",
    flag: "flags/tur.png",
  ),
  CountryCodesModel(
    countryCode: "TM",
    name: "Turkmenistan",
    callingCode: "+993",
    flag: "flags/tkm.png",
  ),
  CountryCodesModel(
    countryCode: "TC",
    name: "Turks and Caicos Islands",
    callingCode: "+1649",
    flag: "flags/tca.png",
  ),
  CountryCodesModel(
    countryCode: "TV",
    name: "Tuvalu",
    callingCode: "+688",
    flag: "flags/tuv.png",
  ),
  CountryCodesModel(
    countryCode: "UG",
    name: "Uganda",
    callingCode: "+256",
    flag: "flags/uga.png",
  ),
  CountryCodesModel(
    countryCode: "UA",
    name: "Ukraine",
    callingCode: "+380",
    flag: "flags/ukr.png",
  ),
  CountryCodesModel(
    countryCode: "AE",
    name: "United Arab Emirates",
    callingCode: "+971",
    flag: "flags/are.png",
  ),
  CountryCodesModel(
    countryCode: "GB",
    name: "United Kingdom of Great Britain and Northern Ireland",
    callingCode: "+44",
    flag: "flags/gbr.png",
  ),
  CountryCodesModel(
    countryCode: "US",
    name: "United States of America",
    callingCode: "+1",
    flag: "flags/usa.png",
  ),
  CountryCodesModel(
    countryCode: "UY",
    name: "Uruguay",
    callingCode: "+598",
    flag: "flags/ury.png",
  ),
  CountryCodesModel(
    countryCode: "UZ",
    name: "Uzbekistan",
    callingCode: "+998",
    flag: "flags/uzb.png",
  ),
  CountryCodesModel(
    countryCode: "VU",
    name: "Vanuatu",
    callingCode: "+678",
    flag: "flags/vut.png",
  ),
  CountryCodesModel(
    countryCode: "VE",
    name: "Venezuela (Bolivarian Republic of,)",
    callingCode: "+58",
    flag: "flags/ven.png",
  ),
  CountryCodesModel(
    countryCode: "VN",
    name: "Viet Nam",
    callingCode: "+84",
    flag: "flags/vnm.png",
  ),
  CountryCodesModel(
    countryCode: "WF",
    name: "Wallis and Futuna",
    callingCode: "+681",
    flag: "flags/wlf.png",
  ),
  CountryCodesModel(
    countryCode: "EH",
    name: "Western Sahara",
    callingCode: "+212",
    flag: "flags/esh.png",
  ),
  CountryCodesModel(
    countryCode: "YE",
    name: "Yemen",
    callingCode: "+967",
    flag: "flags/yem.png",
  ),
  CountryCodesModel(
    countryCode: "ZM",
    name: "Zambia",
    callingCode: "+260",
    flag: "flags/zmb.png",
  ),
  CountryCodesModel(
    countryCode: "ZW",
    name: "Zimbabwe",
    callingCode: "+263",
    flag: "flags/zwe.png",
  ),
];
